

create table schema1.domain_on_schema1 (
	id bigint generated by default as identity, 
	description varchar(255) not null,
	primary key (id)
);
alter table schema1.domain_on_schema1 add constraint UK_schema1 unique (description);

create table schema2.domain_on_schema2 (
	id bigint generated by default as identity, 
	description varchar(255) not null,
	primary key (id)
);
alter table schema2.domain_on_schema2 add constraint UK_schema2 unique (description);
